# This file was generated by https://github.com/lionello/dub2nix v0.2.6
{
  targets = [
    { name = "zmqd@1.2.0"; }
  ];
packages = [ 
{
  fetch = {
    type = "url";
    url = "https://code.dlang.org/packages/zmqd/1.2.0.zip";
    version = "1.2.0";
    sha256 = "0r68wwcmda9j68ca4p5lgqkpcs4xp56pdxlifsljfyf8py1pjm6a";
    name = "zmqd-1.2.0.zip";
    path =  "/nix/store/hvdd829fac1h51vff4gdvwcgglc53kkn-1.2.0.zip";
  };
}
{
  fetch = {
    type = "url";
    url = "https://code.dlang.org/packages/zeromq/6.1.2+zmq-4-3-2.zip";
    version = "6.1.2+zmq-4-3-2";
    name = "zeromq-6.1.2+zmq-4-3-2.zip";
    sha256 = "0hhwmajl0rxz44y152qgvc4ch1gscw32klc1qaa819sllmv2qvsc";
    path = "/nix/store/1nn5fm1v8wa9v3vlwws65m5cmygvy5zk-6.1.2+zmq-4-3-2.zip";
  };
}
];
}
